* 全新的开始

我今年32了，是个程序员，我从来没有像现在如此焦虑过。

我和老婆是在16年就结婚了，我们老家相距600多公里，我家在湖北一个小山村，她家是许昌农村的。我老家交通闭塞，到市区还要坐3个多小时大巴，考虑到现实情况，我毅然同意老婆在许昌买了房。说实话，不买房我也娶不上媳妇了。可能就因为这，我和我爸关系变得很紧张，一不小心就会触到导火索（我是单亲家庭，我妈妈在我6岁的时候就去世了，我爸常年在外打工，我和我爸一年都不能见几次面，我爸也是个闷葫芦，也很不会说话，在老家也不是很讨喜，就是一个闷头干活的老实人），从工作后，我和我爸沟通的次数越来越少了，至此，我都不愿意给我爸打电话了，我也是个内向沉默寡言的人，和我爸也没什么话说。说实在的，我很想和我爸多沟通沟通，希望能父慈子孝，但碍于父子两都这个性格，真是八字不合啊。我爸渐渐老去，身体也越来越差，性格也越来越难相处，以后毕竟是需要一起生活的，我老婆和我爸关系也很紧张，实在是很头疼。幸好我有个好老婆，虽然内心不是很对付，但是还是识大体的人，知道啥事该做，啥事不该做，当我和爸产生矛盾时，还是会疏导我，让我和他多沟通，摆正态度。

哎，这个事也只能走一步算一步了，现在我爸喜欢做啥事就由他了，只希望身体健康，每天过的能顺意点。

今年是2021年，她也31岁了，头上也长起了白发，时常有空就让我帮她拔，由于她头发特别密，可能遗传的原因吧，白发长得特别快，根本拔不完，每次把表面的拔些后我就会糊弄说拔完了。看着她的白发，还有我渐秃的头顶，就会时刻提醒自己已经不再年轻，女生的最佳生育年纪是30岁以前，我精子质量差，不晓得能够怀上孕不，每次老婆提到以后小孩的事时，就给我莫大的压力，我就觉得对不起她，不知这会不会成为我们一生的遗憾。

我很无趣，不懂浪漫，不会聊天，不会挣钱，只知听老婆的话，不知老婆大人有没有后悔和我结婚。

现在的社会现状，35岁对职场中的人来说是个坎绝对不是危言耸听，我这资质平平的可以说是以后很危险，将来失业了，我拿啥来养家? 难道外卖滴滴就是结局？我可能在这两个行业里更没竞争力，人不机灵，整天显得无精打采。然而出租车司机！我拿到驾照后就没开过车，现在让我开车我都不敢，能不能当个出租车司机我自己心里也没底。

依然记得年少时的梦想（本来打的是理想这个词），最终只是做梦。 逐渐活成了自己最讨厌的样子。

每个普通人都活的很辛苦，假努力有啥用，骗鬼呢？ 我的焦虑全来自自己的懈怠和对未来暗淡的害怕，要想有一个无悔的人生，从现在开始，放弃一切借口，行动起来，万事开头难，这个十年我要做一个积累和输出的十年，未来可期。

只要每天能真真的进步一点点，提前做好准备，危机可以不慌不忙的化解。

技能是通过练习实践来进步的，我要始终记住一句话，没有实践还不如不学，要进行有效的学习

今天，2021年已经过了一大半了，希望从今天开始，自己不再迷茫，不再焦虑，扎稳马步，坚定的往前行。前面的路并没有豺狼虎豹，只有美丽的风景，要想欣赏美景，那你要有一颗美丽的心。

今天，我认识到了自己的担子，只有前行才能化解危机。在此，警示自己，不忘初心

